### ISSUE TITLE
Use CI for deployment of grad.then()

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#82]
# Lets discuss deployment

There are not many deployment options available for teams to use, I ran through several this morning.

And they will all need either a shared account or a paid team account.

Surge.sh was the most straightforward to set up but appears there's no team option but you can us CI there are several options but I think Travis CI is the most straight forward:

https://surge.sh/help/integrating-with-travis-ci

https://travis-ci.org/chingu-voyage3/grad.then

A `.yml` file will need to be added to the root of the project:

```yml
language: node_js
node_js:
  - "node"

deploy:
  provider: surge
  project: ./public/
  domain: grad-then.surge.sh  
```
